### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Arjaes** [albertodonato/ads-b-snap#1]
Your ADS-B program a SNAP installed program is working as expected, 
however configuration is difficult to find online, since using SNAP alters all the usual folder that contain configuration files.
I found some in the read only SNAP folder, but of course could not alter them.

I just gave up for the day.

Por Favor apúntame a esa información.
Thanks for the effort.......

Robert J Sori
J is for Javier, I am Cuban

**Comment by albertodonato** [comment]
Hi, configuration with the snap is done through the `snap set` commands described in the README.

Could you please specify what kind of configuration you want to change?

**Comment by Arjaes** [comment]
The lon and lat coordinates, I did set the command via snap
And it accepted the change.

But the map still begins in Nee York and the H home button sends the map back to the New York area.

That's when I tried to hard code the info into the tar1090 configuration.

Bob Sori




________________________________

**Comment by albertodonato** [comment]
This is quite strange. I wonder if it's not accepting the coordinates because of the format. It should be something like
```
snap set ads-b coord.lat=xx.xxxx coord.lon=yy.yyyy
```
Did you use this format?

**Comment by Arjaes** [comment]
Yes, I am not at my laptop, I believe I enclosed them in quotes ""
________________________________

**Comment by Arjaes** [comment]
***@***.*** 22:18:11 /snap $:  
sudo snap set ads-b coord.lat=36.2191622

***@***.*** 22:19:22 /snap $:  
sudo snap set ads-b coord.long=-115.3197568

***@***.*** 22:19:51 /snap $:  


I used these commands

**Comment by albertodonato** [comment]
It seems you might have a typo there `coord.long` vs `coord.lon`.
