### ISSUE TITLE
Problems with decoder / receiver / backend

### ISSUE THREAD

**Issue by bi3mw** [albertodonato/ads-b-snap#3]
Hello, 
I have a problem when starting tar1090. The following error message appears:

Problem fetching data from the server:
Seems the decoder / receiver / backend isn't working correctly ! 

I have connected a SDRplay RSPdx. Is this device not supported ?

**Comment by albertodonato** [comment]
Can you please paste the output of the following commands:
- `snap services ads-b`
- `sudo journalctl -ef -u snap.ads-b.dump1090`

I've only tested the snap with an RTL-SDR device, not sure if it works with others

**Comment by bi3mw** [comment]
Okay, here's the output:

snap services ads-b

Dienst                Startvorgang  Aktuell  Notizen
ads-b.adsbxfeed       aktiviert     aktiv    -
ads-b.adsbxfeed-mlat  aktiviert     inaktiv  -
ads-b.dump1090        aktiviert     inaktiv  -
ads-b.fr24feed        aktiviert     inaktiv  -
ads-b.lighttpd        aktiviert     aktiv    - 


sudo journalctl -ef -u snap.ads-b.dump1090

systemd[1]: Started Service for snap application ads-b.dump1090.
ads-b.dump1090[121744]: Sat Jan 20 15:55:31 2024 CET  dump1090-fa unknown starting up.
ads-b.dump1090[121744]: rtlsdr: no supported devices found.
systemd[1]: snap.ads-b.dump1090.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: snap.ads-b.dump1090.service: Failed with result 'exit-code'.
systemd[1]: snap.ads-b.dump1090.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped Service for snap application ads-b.dump1090.
systemd[1]: Started Service for snap application ads-b.dump1090.
ads-b.dump1090[122005]: Sat Jan 20 15:55:31 2024 CET  dump1090-fa unknown starting up.
ads-b.dump1090[122005]: rtlsdr: no supported devices found.
systemd[1]: snap.ads-b.dump1090.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: snap.ads-b.dump1090.service: Failed with result 'exit-code'.
systemd[1]: snap.ads-b.dump1090.service: Scheduled restart job, restart counter is at 2.
systemd[1]: Stopped Service for snap application ads-b.dump1090.
systemd[1]: Started Service for snap application ads-b.dump1090.
ads-b.dump1090[122062]: Sat Jan 20 15:55:31 2024 CET  dump1090-fa unknown starting up.
ads-b.dump1090[122062]: rtlsdr: no supported devices found.
systemd[1]: snap.ads-b.dump1090.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: snap.ads-b.dump1090.service: Failed with result 'exit-code'.
systemd[1]: snap.ads-b.dump1090.service: Scheduled restart job, restart counter is at 3.
systemd[1]: Stopped Service for snap application ads-b.dump1090.
systemd[1]: Started Service for snap application ads-b.dump1090.
ads-b.dump1090[122100]: Sat Jan 20 15:55:32 2024 CET  dump1090-fa unknown starting up.
ads-b.dump1090[122100]: rtlsdr: no supported devices found.
systemd[1]: snap.ads-b.dump1090.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: snap.ads-b.dump1090.service: Failed with result 'exit-code'.
systemd[1]: snap.ads-b.dump1090.service: Scheduled restart job, restart counter is at 4.
systemd[1]: Stopped Service for snap application ads-b.dump1090.
systemd[1]: Started Service for snap application ads-b.dump1090.
ads-b.dump1090[122139]: Sat Jan 20 15:55:32 2024 CET  dump1090-fa unknown starting up.
ads-b.dump1090[122139]: rtlsdr: no supported devices found.
systemd[1]: snap.ads-b.dump1090.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: snap.ads-b.dump1090.service: Failed with result 'exit-code'.
snap.ads-b.dump1090.service: Scheduled restart job, restart counter is at 5.
systemd[1]: Stopped Service for snap application ads-b.dump1090.
systemd[1]: snap.ads-b.dump1090.service: Start request repeated too quickly.
systemd[1]: snap.ads-b.dump1090.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Service for snap application ads-b.dump1090.

**Comment by albertodonato** [comment]
It seems the device is not supported:

```
ads-b.dump1090[122139]: Sat Jan 20 15:55:32 2024 CET dump1090-fa unknown starting up.
ads-b.dump1090[122139]: rtlsdr: no supported devices found.
```

**Comment by bi3mw** [comment]
All right, thank you.

**Comment by albertodonato** [comment]
You could try finding out if the device can actually be supported by dump1090, and what compile options are needed in that case.
